### ISSUE TITLE
Devices not detected

### ISSUE THREAD

**Issue by Thane5** [endurabyte/nmtp#1]
i made a quick test while i was testing out various MTP libraries.

during my first run with NMTP i was confused that this code printed nothing to the console.

```
using var list = new Nmtp.RawDeviceList();
foreach(Nmtp.RawDevice device in list)
{
      Console.WriteLine(device);
}
```

turns out, this library failed to detect any of my devices, as the list was 0.
```
using var list = new Nmtp.RawDeviceList();
        Console.WriteLine(list.Count());
```

During this test i had a fujifilm camera, and an empty SD card reader connected. Both were detected just fine by windows explorer and other MTP/WPD libraries.

The same issue actually arised with LibMtpSharp as well, but i noticed that NMTP has more recent activity.

**Comment by nref** [comment]
Thanks for posting the issue. 

The real experts are over at [libmtp](https://github.com/libmtp/libmtp). This is a fork mainly for the purpose of enabling [FitEdit](https://github.com/endurabyte/fitedit) to get files off of Garmin watches. 

One problem may be that the version of `libmtp` used here is 174 commits behind. I can try to update the lib, but I have no way to check if it it fixed your issue. Would that be helpful?

**Comment by Thane5** [comment]
i would gladly do another test run if you updated the library.

**Comment by nref** [comment]
I'll report back ASAP

**Comment by nref** [comment]
So I checked on the latest libmtp, and while they have added a handful of devices, they have not added any Fujifilm devices. The design of libmtp is such that if your device is not named in the `music-players.h` file (a historical name from when only mp3 players used MTP) at compile time, then libmtp will not recognize it.

I can add it for you. I would need the device name, the USB Vendor ID (VID) and the Product ID (PID). If you are on Windows, this can be found in Device Manager: 

![image](https://github.com/user-attachments/assets/c2968224-78b2-4db2-9566-7dc9472f8737)

There is also `mtp-detect.exe` (or `mtp-detect` on macOS and Linux) which I could provide for you to run:

```
F:\repos\nmtp\lib\win-x64\output\bin> .\mtp-detect.exe
Unable to determine user's home directory, MTPZ disabled.
libmtp version: 1.1.21

Listing raw device(s)
Device 0 (VID=091e and PID=4e44) is a Garmin Forerunner 945 LTE.
   Found 1 device(s):
   Garmin: Forerunner 945 LTE (091e:4e44) @ bus 3, dev 1
```

**Comment by Thane5** [comment]
Thank you for checking, but i don't think adding devices manually now would be very useful for this repository or for my project.
